maintenance.title=Maintenance
maintenance.disconnect.bypass=You are currently bypassing maintenance mode.
maintenance.disconnect.title=This server is currently in maintenance.
maintenance.disconnect.remaining=Approximated duration: %s
maintenance.disconnect.remaining.generic=Please try again later.
maintenance.disconnect.messageFromServer=Server message: %s
maintenance.command.velocity.status=You've %1$s global maintenance mode.
maintenance.command.status.true=enabled
maintenance.command.status.false=disabled
maintenance.command.velocity.status.other=%3$s has %1$s global maintenance mode.
maintenance.command.velocity.status.fail=Global maintenance mode is already %1$s.
console.name=Console
maintenance.command.velocity.message.set=You've set the global maintenance message to %1$s.
maintenance.command.velocity.message.unset=You've reset the global maintenance message.
maintenance.command.velocity.message.set.other=%3$s set the global maintenance message to %1$s.
maintenance.command.velocity.message.unset.other=%2$s reset the global maintenance message.
maintenance.command.velocity.duration.set=You've set the global maintenance duration to %2$s.
maintenance.command.velocity.duration.set.other=%3$s set the global maintenance duration to %2$s.
maintenance.command.velocity.duration.unset=You've set the global maintenance duration to indefinite.
maintenance.command.velocity.duration.unset.other=%2$s set the global maintenance duration to indefinite.
maintenance.command.velocity.duration.current=Global maintenance duration is currently %2$s.
maintenance.command.velocity.duration.current.indefinite=Global maintenance duration is currently indefinite.
maintenance.disconnect.title.paper=%s is currently in maintenance.
maintenance.command.paper.duration.set=You've set the maintenance duration for %1$s to %2$s.
maintenance.command.paper.duration.set.other=%3$s set the maintenance duration of %1$s to %2$s.
maintenance.command.paper.status=You've %1$s maintenance mode for %2$s.
maintenance.command.paper.status.other=%3$s has %1$s maintenance mode for %2$s.
maintenance.command.paper.status.fail=Maintenance mode for %2$s is already %1$s.
maintenance.command.paper.duration.unset=You've set the maintenance duration for %1$s to indefinite.
maintenance.command.paper.duration.unset.other=%2$s set the maintenance duration for %1$s to indefinite.
maintenance.command.paper.duration.current=The maintenance duration for %1$s is currently %2$s.
maintenance.command.paper.duration.current.indefinite=The maintenance duration for %1$s is currently indefinite.
maintenance.command.paper.message.set=You've set the maintenance message for %2$s to %1$s.
maintenance.command.paper.message.set.other=%3$s set the maintenance message for %2$s to %1$s.
maintenance.command.paper.message.unset=You've reset the maintenance message for %1$s.
maintenance.command.paper.message.unset.other=%2$s reset the maintenance message for %1$s.
maintenance.command.velocity.enforce=You've enforced global maintenance mode.
maintenance.command.velocity.enforce.other=%2$s has enforced global maintenance mode.
maintenance.command.paper.enforce=You've enforced maintenance mode for %1$s.
maintenance.command.paper.enforce.other=%2$s enforced maintenance mode for %1$s.
maintenance.command.enforce.fail=Maintenance mode must be enabled to be enforced.
maintenance.command.velocity.status.current=Global maintenance mode is currently %2$s.
maintenance.command.velocity.message.current.none=The global maintenance message is currently not set.
maintenance.command.paper.status.current=Maintenance mode for %1$s is currently %2$s.
maintenance.command.velocity.message.current=The global maintenance message is currently set to %2$s.
maintenance.command.paper.message.current=The maintenance message for %1$s is currently set to %2$s.
maintenance.command.paper.message.current.none=The maintenance message for %1$s is currently not set.
maintenance.command.list.current=Listing %1$s servers in maintenance mode: %2$s
maintenance.command.list.none=There are no servers in maintenance mode to be listed.

